data:
  batch_size: 16
  
model:
  config: configs/model.yaml

epochs: 50 # 训练多少个epoch
lr_adjust_epoch: 25 # 学习率调整的epoch，降为原有的10%
batch_print_interval: 100 # 打印间隔，以batch为单位
checkpoint_save_interval: 10 # 模型保存间隔，以epoch为单位
save_path: './checkpoints/c_v1'  # 模型保存路径
use_cfg: True  # 是否使用classifier-free guidance，开启就可以训练条件生成模型了
device: 'cuda' # cuda、cpu、mps(only macbook)
